version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/deploy
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/afterInstall.sh
      runas: ec2-user